### ISSUE TITLE
No link passed when shared

### ISSUE THREAD

**Issue by ztalk112** [arjunkomath/Feline-for-Product-Hunt#7]
Hi,

Love the fresh new look after your recent update, however I have an issue when sharing PH posts on Android 6.0.1 (Nexus 5).

Regardless of the vehicle used (tested with Gmail, Messenger and Pushbullet), no link is passed in the share . . . only the short post description.

(Note, my strong preference is that the PH post itself should be shared, not the Get It website link).

Cheers.

![sample share](https://user-images.githubusercontent.com/30450078/28598465-dbd9d0ae-71f7-11e7-90ca-a878d214ff95.png)

**Comment by arjunkomath** [comment]
Fixed in Production Release 2.2.1
